c.ModeDataManager.nclasses = 1
c.ModeDataManager.reduce_sparsity = 0.0
c.ModeDataManager.subsample_index = 1
c.ModeDataManager.class_file = "NONE"
c.ModeDataManager.cache_dir = "/Volumes/archive/spectraclass/"
c.ModeDataManager.data_dir = "/Volumes/archive/data/"
c.ModeDataManager.modelkey = "neon-150-32.aec"
c.DataManager.proc_type = "cpu"
c.DataManager.refresh_data = False
c.DataManager.labels_dset = "labels"
c.DataManager.ncores = 4
c.DataManager.preprocess = False
c.TileManager._block_selection = (1, 1)
c.TileManager.block_size = 250
c.TileManager.mask_class = 0
c.TileManager.autoprocess = False
c.TileManager.reprocess = False
c.ReductionManager.alpha = 0.9
c.ReductionManager.init = "random"
c.ReductionManager.loss = "mean_squared_error"
c.ReductionManager.ndim = 3
c.ReductionManager.nepochs = 200
c.ReductionManager.target_weight = 0.5
c.ActivationFlowManager.metric = "cosine"
c.ActivationFlowManager.nneighbors = 5
c.PointCloudManager.color_map = "gist_rainbow"
c.MapManager.init_band = 10
c.MapManager.lower_threshold = 0.0
c.MapManager.upper_threshold = 1.0
c.TextureManager.textures = [{'type': 'gabor', 'bands': [1, 3], 'nfeatures': 1}, {'type': 'glcm', 'bands': [1], 'features': ['homogeneity', 'energy']}]
c.ClusterManager.modelid = "kmeans"
c.ClusterManager.nclusters = 10
c.ClusterManager.random_state = 0
c.ClassificationManager.mid = "mlp"
c.ClassificationManager.nfeatures = 32
c.ClassificationManager.nepochs = 10

